SET
	SEARCH_PATH TO SOCIALNET7;

WITH
	END_METRIC AS (
		SELECT
			ACCOUNT_ID,
			METRIC_TIME,
			METRIC_VALUE AS END_VALUE
		FROM
			METRIC M
			INNER JOIN METRIC_NAME N ON M.METRIC_NAME_ID = N.METRIC_NAME_ID
			AND N.METRIC_NAME = 'newfriend_per_month'
			AND METRIC_TIME BETWEEN '2020-04-01' AND '2020-05-10'
	),
	START_METRIC AS (
		SELECT
			ACCOUNT_ID,
			METRIC_TIME,
			METRIC_VALUE AS START_VALUE
		FROM
			METRIC M
			INNER JOIN METRIC_NAME N ON M.METRIC_NAME_ID = N.METRIC_NAME_ID
			AND N.METRIC_NAME = 'newfriend_per_month'
			AND METRIC_TIME BETWEEN '2020-04-01'::TIMESTAMP - INTERVAL '4 week' AND '2020-05-10'::TIMESTAMP - INTERVAL '4 week'
		ORDER BY
			METRIC_TIME
	)
SELECT
	S.ACCOUNT_ID,
	S.METRIC_TIME + INTERVAL '4 week' AS END_TIME,
	START_VALUE,
	END_VALUE,
	(COALESCE(END_VALUE, 0.0) / START_VALUE) - 1.0 AS PERCENT_CHANGE_PER_MONTH
FROM
	START_METRIC S
	LEFT OUTER JOIN END_METRIC E ON S.ACCOUNT_ID = E.ACCOUNT_ID
	AND E.METRIC_TIME = (S.METRIC_TIME + INTERVAL '4 week')
WHERE
	START_VALUE > 0