SET
	SEARCH_PATH TO SOCIALNET7;

WITH
	NUM_METRIC AS (
		SELECT
			ACCOUNT_ID,
			METRIC_TIME,
			METRIC_VALUE AS NUM_VALUE
		FROM
			METRIC M
			INNER JOIN METRIC_NAME N ON M.METRIC_NAME_ID = N.METRIC_NAME_ID
			AND N.METRIC_NAME = 'adview_per_month'
			AND M.METRIC_TIME BETWEEN '2020-04-01' AND '2020-05-10'
		ORDER BY
			METRIC_TIME
	),
	DEN_METRIC AS (
		SELECT
			ACCOUNT_ID,
			METRIC_TIME,
			METRIC_VALUE AS DEN_VALUE
		FROM
			METRIC M
			INNER JOIN METRIC_NAME N ON M.METRIC_NAME_ID = N.METRIC_NAME_ID
			AND N.METRIC_NAME = 'post_per_month'
			AND M.METRIC_TIME BETWEEN '2020-04-01' AND '2020-05-10'
		ORDER BY
			METRIC_TIME
	)
SELECT
	D.ACCOUNT_ID,
	D.METRIC_TIME,
	NUM_VALUE,
	DEN_VALUE,
	CASE
		WHEN DEN_VALUE > 0 THEN COALESCE(NUM_VALUE, 0.0) / DEN_VALUE
		ELSE 0
	END AS METRIC_VALUE
FROM
	DEN_METRIC D
	LEFT OUTER JOIN NUM_METRIC N ON N.ACCOUNT_ID = D.ACCOUNT_ID
	AND N.METRIC_TIME = D.METRIC_TIME