SET
	SEARCH_PATH TO SOCIALNET7;

SELECT
	ACCOUNT_ID,
	METRIC_TIME,
	--STRING_AGG(METRIC_VALUE::TEXT, '+') AS METRIC_SUM,
	15,
	SUM(METRIC_VALUE) AS METRIC_TOTAL
FROM
	METRIC M
	INNER JOIN METRIC_NAME N ON M.METRIC_NAME_ID = N.METRIC_NAME_ID
	AND METRIC_NAME IN ('like_per_month', 'dislike_per_month')
WHERE
	METRIC_TIME BETWEEN '2020-03-01' AND '2020-04-01'
GROUP BY
	ACCOUNT_ID,
	METRIC_TIME